name: PushPlus Birthday Notice
# 设置工作流的名称

on:
  schedule:
    # 触发器设置，基于定时任务触发
    - cron: '0 2 9 * *'
      # cron表达式，表示在北京时间每天上午10点（UTC时间2点）触发此工作流
  # 允许手动触发工作流
  workflow_dispatch:
    # 添加一个手动触发工作流的方式

jobs:
  build:
    # 定义一个名为build的任务
    runs-on: ubuntu-latest
    # 指定此任务将在最新的Ubuntu镜像上运行

    steps:
    - name: Checkout code
      # 步骤名称：检出代码
      uses: actions/checkout@v3
      # 使用GitHub Actions提供的checkout动作来检出代码到工作区

    - name: Set up Python
      # 步骤名称：设置Python环境
      uses: actions/setup-python@v4
      # 使用GitHub Actions提供的setup-python动作来安装Python环境
      with:
        python-version: '3.x' # 使用最新的Python 3版本

    - name: Install dependencies
      # 步骤名称：安装依赖
      run: |
        # 执行多行命令
        python -m pip install --upgrade pip
        # 升级pip到最新版本
        pip install requests
        # 安装requests库
        pip install lunar-calendar # 假设lunardate包在此名称下发布或使用正确的包名
        # 安装lunar-calendar库（假设该库名正确）

    - name: Run birthday reminder script
      # 步骤名称：运行生日提醒脚本
      run: python pushplus/birthday_notice.py
      # 运行指定的Python脚本来执行生日提醒逻辑
      env:
        # 如果脚本中使用了环境变量（例如API密钥），在这里定义它们
        # PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
        # 注意：如果使用PushPlus API需要认证，确保设置正确的环境变量
        # 在这里定义环境变量，使用仓库的Secrets功能来安全地存储敏感信息
